# Generated by Django 4.2.13 on 2024-05-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='role',
            new_name='role1',
        ),
    ]
