# Generated by Django 4.2.13 on 2024-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_role1_person_role_person_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('product_price', models.IntegerField(default=0)),
                ('product_GST', models.FloatField(default=0)),
                ('food_product', models.IntegerField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
