# Generated by Django 4.2.13 on 2024-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_product',
            field=models.BooleanField(default=False),
        ),
    ]
