# Generated by Django 4.2.13 on 2024-05-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_food_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_GST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
