# Generated by Django 4.2.13 on 2024-05-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_GST',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
